apiVersion: apps/v1
kind: Deployment
metadata:
  name:  working-deployment
  labels:
    name: working-app-pod
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: working-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: working-app-pod
      labels:
        name: working-app-pod
        app: demo-voting-app
    spec:
      containers:
      - name: working-app-pod
        image: dockersamples/examplevotingapp_worker